AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions used to demonstrate Lambda invoke operator with S3 log extension

Globals:
  Function:
    MemorySize: 128
    Timeout: 30
    Runtime: python3.8
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: airflow
        LOG_LEVEL: INFO
    Tags:
      Application: LambdaInvokeOperatorDemo

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-lambda-function
      Description: Example lambda function
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:26
  ExampleFunctionAsyncConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref ExampleFunction
      MaximumRetryAttempts: 0
      Qualifier: "$LATEST"
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ExampleFunction}"
      RetentionInDays: 1

Outputs:
  ExampleFunction:
    Value: !Ref ExampleFunction
    Description: Example lambda function ARN
